Added Condition to deploy-after-tests.yml

diff --git a/.github/workflows/deploy-after-tests.yml b/.github/workflows/deploy-after-tests.yml
--- a/.github/workflows/deploy-after-tests.yml
+++ b/.github/workflows/deploy-after-tests.yml
@@ -9,5 +9,16 @@ jobs:
   code-checkout:
     runs-on: ubuntu-latest
     steps:
+      - name: Workflow succeeded Check
+        run: | 
+          if [ "${{ github.event.workflow_run.conclusion}}" == 'success'  ]; then
+            echo "Workflow Succedded"
+          else
+            echo ":warning:: Failed"
+            exit 1
+          fi
+
       - name: Checkout Code
         uses: actions/checkout@v6
+
+      
